<?php

/**
 * Settings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Settings extends BaseSettings
{
	public function getPlayingFieldCenterLatLong() {
		$return["latitude"] = $this->playingFieldUpperLeftLatitude - (abs($this->playingFieldUpperLeftLatitude - $this->playingFieldLowerRightLatitude) / 2);
		$return["longitude"] = $this->playingFieldLowerRightLongitude - (abs($this->playingFieldUpperLeftLongitude - $this->playingFieldLowerRightLongitude) / 2);
		
		return $return;
	}
	
	public function findNewBonusGoal($forceSearch = false) {
		if (empty($this->bonusGoal) || $this->BonusGoal->battery <= 0 || $forceSearch) {
			$randomActiveNode = Doctrine_Query::create()->select("*, RANDOM() AS rand")->from("Player")->where("role = ? AND battery > ?", array(2, 0))->orderBy("rand")->execute()->getFirst();

			if (!empty($randomActiveNode)) {
				$this->bonusGoal = $randomActiveNode->id;
			} else {
				$this->bonusGoal = null;
			}
	
			$this->save();
		}
	}
}