package de.unipotsdam.nexplorer.server.persistence.hibernate.dto;

// Generated 19.09.2012 13:58:49 by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AodvRouteRequestBufferEntries generated by hbm2java
 */
@Entity
@Table(name = "aodv_route_request_buffer_entries")
public class AodvRouteRequestBufferEntries implements java.io.Serializable {

	private Long id;
	private Long nodeId;
	private Long sourceId;
	private Long sequenceNumber;
	private Integer version;

	public AodvRouteRequestBufferEntries() {
	}

	public AodvRouteRequestBufferEntries(Long nodeId, Long sourceId, Long sequenceNumber) {
		this.nodeId = nodeId;
		this.sourceId = sourceId;
		this.sequenceNumber = sequenceNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "node_id")
	public Long getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Long nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "source_id")
	public Long getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(Long sourceId) {
		this.sourceId = sourceId;
	}

	@Column(name = "sequence_number")
	public Long getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(Long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	@Version
	@Column(name = "OPTLOCK")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		Long id = getId();
		if (id != null) {
			if (id > Integer.MAX_VALUE) {
				return Integer.MAX_VALUE;
			} else if (id < Integer.MIN_VALUE) {
				return Integer.MIN_VALUE;
			} else {
				long tmp = id;
				return (int) tmp;
			}
		} else {
			return 1;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj.getClass() != getClass()) {
			return false;
		}

		AodvRouteRequestBufferEntries other = (AodvRouteRequestBufferEntries) obj;
		if (other.id != id) {
			return false;
		}
		if (other.nodeId != nodeId) {
			return false;
		}
		if (other.sequenceNumber != sequenceNumber) {
			return false;
		}
		if (other.sourceId != sourceId) {
			return false;
		}
		if (other.version != version) {
			return false;
		}

		return true;
	}
}
