package de.unipotsdam.nexplorer.server.persistence.hibernate.dto;

// Generated 19.09.2012 13:58:49 by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AodvRoutingTableEntries generated by hbm2java
 */
@Entity
@Table(name = "aodv_routing_table_entries")
public class AodvRoutingTableEntries implements java.io.Serializable {

	private Long id;
	private Long timestamp;
	private Long nodeId;
	private Long destinationId;
	private Long nextHopId;
	private Long destinationSequenceNumber;
	private Long hopCount;
	private Integer version;

	public AodvRoutingTableEntries() {
	}

	public AodvRoutingTableEntries(Long nodeId, Long destinationId, Long nextHopId, Long destinationSequenceNumber, Long hopCount) {
		this.nodeId = nodeId;
		this.destinationId = destinationId;
		this.nextHopId = nextHopId;
		this.destinationSequenceNumber = destinationSequenceNumber;
		this.hopCount = hopCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "timestamp")
	public Long getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Long timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "node_id")
	public Long getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Long nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "destination_id")
	public Long getDestinationId() {
		return this.destinationId;
	}

	public void setDestinationId(Long destinationId) {
		this.destinationId = destinationId;
	}

	@Column(name = "next_hop_id")
	public Long getNextHopId() {
		return this.nextHopId;
	}

	public void setNextHopId(Long nextHopId) {
		this.nextHopId = nextHopId;
	}

	@Column(name = "destination_sequence_number")
	public Long getDestinationSequenceNumber() {
		return this.destinationSequenceNumber;
	}

	public void setDestinationSequenceNumber(Long destinationSequenceNumber) {
		this.destinationSequenceNumber = destinationSequenceNumber;
	}

	@Column(name = "hop_count")
	public Long getHopCount() {
		return this.hopCount;
	}

	public void setHopCount(Long hopCount) {
		this.hopCount = hopCount;
	}

	@Version
	@Column(name = "OPTLOCK")
	public Integer getVersion() {
		return this.version;
	}
	
	public void setVersion(Integer version) {
		this.version = version;
	}
}
