package de.unipotsdam.nexplorer.server.persistence.hibernate.dto;

// Generated 19.09.2012 13:58:49 by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AodvRoutingMessages generated by hbm2java
 */
@Entity
@Table(name = "aodv_routing_messages")
public class AodvRoutingMessages implements java.io.Serializable {

	private Long id;
	private Long currentNodeId;
	private String type;
	private Long sourceId;
	private Long destinationId;
	private Long lifespan;
	private Long sequenceNumber;
	private Long hopCount;
	private String passedNodes;
	private Long processingRound;
	private Integer version;

	public AodvRoutingMessages() {
	}

	public AodvRoutingMessages(Long currentNodeId, String type, Long sourceId, Long destinationId, Long lifespan, Long sequenceNumber, Long hopCount, String passedNodes, Long processingRound) {
		this.currentNodeId = currentNodeId;
		this.type = type;
		this.sourceId = sourceId;
		this.destinationId = destinationId;
		this.lifespan = lifespan;
		this.sequenceNumber = sequenceNumber;
		this.hopCount = hopCount;
		this.passedNodes = passedNodes;
		this.processingRound = processingRound;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "current_node_id")
	public Long getCurrentNodeId() {
		return this.currentNodeId;
	}

	public void setCurrentNodeId(Long currentNodeId) {
		this.currentNodeId = currentNodeId;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "source_id")
	public Long getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(Long sourceId) {
		this.sourceId = sourceId;
	}

	@Column(name = "destination_id")
	public Long getDestinationId() {
		return this.destinationId;
	}

	public void setDestinationId(Long destinationId) {
		this.destinationId = destinationId;
	}

	@Column(name = "lifespan")
	public Long getLifespan() {
		return this.lifespan;
	}

	public void setLifespan(Long lifespan) {
		this.lifespan = lifespan;
	}

	@Column(name = "sequence_number")
	public Long getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(Long sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	@Column(name = "hop_count")
	public Long getHopCount() {
		return this.hopCount;
	}

	public void setHopCount(Long hopCount) {
		this.hopCount = hopCount;
	}

	@Column(name = "passed_nodes")
	public String getPassedNodes() {
		return this.passedNodes;
	}

	public void setPassedNodes(String passedNodes) {
		this.passedNodes = passedNodes;
	}

	@Column(name = "processing_round")
	public Long getProcessingRound() {
		return this.processingRound;
	}

	public void setProcessingRound(Long processingRound) {
		this.processingRound = processingRound;
	}

	@Version
	@Column(name = "OPTLOCK")
	public Integer getVersion() {
		return this.version;
	}
	
	public void setVersion(Integer version) {
		this.version = version;
	}
}
