package de.unipotsdam.nexplorer.server.persistence.hibernate.dto;

// Generated 19.09.2012 13:58:49 by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Neighbours generated by hbm2java
 */
@Entity
@Table(name = "neighbours", uniqueConstraints = @UniqueConstraint(columnNames = { "node_id", "neighbour_id" }))
public class Neighbours implements java.io.Serializable {

	private Long id;
	private Players neighbour;
	private Players node;
	private Integer version;

	public Neighbours() {
	}

	public Neighbours(Players neighbour, Players node) {
		this.neighbour = neighbour;
		this.node = node;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "neighbour_id")
	public Players getNeighbour() {
		return this.neighbour;
	}

	public void setNeighbour(Players neighbour) {
		this.neighbour = neighbour;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node_id")
	public Players getNode() {
		return this.node;
	}

	public void setNode(Players node) {
		this.node = node;
	}

	@Override
	public int hashCode() {
		return 1;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Neighbours other = (Neighbours) obj;

		if (node != other.node)
			return false;
		if (neighbour != other.neighbour)
			return false;

		return true;
	}

	@Version
	@Column(name = "OPTLOCK")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
}
